version: 2

models:
  # =========================
  # DIMENSION TABLES
  # =========================
  - name: dim_zones
    description: >
      Dimension table containing NYC Taxi zone metadata.
      Used for enriching fact tables with borough and zone information.
    
    columns:
      - name: location_id
        description: Unique identifier for taxi zone.
        tests:
          - not_null
          - unique
          - dbt_utils.at_least_one

      - name: borough
        description: Borough where the taxi zone is located.
        tests:
          - not_null

      - name: zone
        description: Name of the taxi pickup/dropoff zone.
        tests:
          - not_null

      - name: service_zone
        description: Taxi service zone classification.

  # =========================
  # FACT TABLES
  # =========================
  - name: fact_monthly_zone_revenue
    description: >
      Fact table containing aggregated monthly revenue for green and yellow taxis.
      Includes month revenue, total trips, service type.
    columns:
      - name: revenue_month
        description: month in which revenue was generated
        tests:
          - dbt_utils.at_least_one

  - name: fact_trips
    description: >
      Fact table containing aggregated metrics for Green and Yellow Taxi trips.
      Includes fare amounts, trip distance, and timestamps.

    columns:
      - name: pickup_location_id
        description: Foreign key to dim_zones.location_id
        tests:
          - dbt_utils.at_least_one
          - not_null
          - relationships:
              to: ref('dim_zones')
              field: location_id

      - name: dropoff_location_id
        description: Foreign key to dim_zones.location_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_zones')
              field: location_id

      - name: pickup_datetime
        description: Pickup timestamp.
        tests:
          - not_null

      - name: dropoff_datetime
        description: Dropoff timestamp.
        tests:
          - not_null

      - name: passenger_count
        description: Number of passengers.
        tests:
          - not_null

      - name: trip_distance
        description: Distance traveled in miles.
        tests:
          - not_null

      - name: total_amount
        description: Total trip charge including fees.
        tests:
          - not_null

  # =========================
  # INTERMEDIATE TABLES
  # =========================
  - name: int_trips_unioned
    description: >
      Combines data from yellow and green taxi data from staging
    columns:
      - name: pickup_datetime
        tests:
          - dbt_utils.at_least_one

  # =========================
  # STAGING TABLES
  # =========================
  - name: stg_green_tripdata
    description: >
      Cleaned and standardized Green Taxi raw trip data.
      Removes invalid records and renames fields.
    
    columns:
      - name: VendorID
        description: Taxi vendor identifier.
        tests:
          - dbt_utils.at_least_one

      - name: pickup_datetime
        description: Pickup timestamp.
        tests:
          - not_null

      - name: pickup_location_id
        description: Pickup location ID.
        tests:
          - not_null

      - name: total_amount
        description: Total trip charge.

  - name: stg_fhv_tripdata
    description: >
      Cleaned and standardized For-Hire Vehicle (FHV) trip data.

    columns:
      - name: dispatching_base_num
        description: FHV dispatch base number.
        tests:
          - dbt_utils.at_least_one

      - name: pickup_datetime
        description: Pickup timestamp.
        tests:
          - not_null

      - name: pickup_location_id
        description: Pickup location ID.